app:
  # 身份码
  idCode: ""
  # access_key
  accessKey: ""
  # access_secret
  accessSecret: ""
  # 项目Id（13位数字）
  appId:
  # 弹幕内容映射为按键时是否忽略大小写（默认忽略大小写）
  ignoreCase: true
  # 按键映射文件路径
  mappingFilePath: "./config/keyMapping.json"
  # 触发方式（awt or jna），由于 GraalVM native image 打包原生镜像时不支持awt，所以默认使用 jna 实现按键模拟
  simMethod: jna