app:
  # 身份码
  idCode: ""
  # access_key
  accessKey: ""
  # access_secret
  accessSecret: ""
  # 项目Id（13位数字）
  appId:
  # 弹幕内容映射为按键时是否忽略大小写（默认忽略大小写）
  ignoreCase: true
  # 按键映射文件路径
  mappingFilePath: "./config/keyMapping.json"
  # 按键执行计划目录
  processDir: "./config/process"
  # 触发方式（awt or jna），由于 GraalVM native image 打包原生镜像时不支持awt，所以默认使用 jna 实现按键模拟
  simMethod: jna
  scheduled:
    # 每次执行process运行间隔
    execution-interval: 1000
    # 工作队列容量
    queue-capacity: 100
    # 拒绝策略，默认 abort-new 抛弃新任务，填其他则抛弃队列中最早添加即将要执行的任务
    rejection-policy: abort-new